name: navigation
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core
  core_ui:
    path: ../core_ui
  auth:
    path: ../features/auth
  home_page:
    path: ../features/home_page
  user_profile:
    path: ../features/user_profile
  scanner:
    path: ../features/scanner
  user_data:
    path: ../features/user_data
  private_folders:
    path: ../features/private_folders
  user_folders:
    path: ../features/user_folders

  auto_route: ^9.2.2

dev_dependencies:
  flutter_lints: ^3.0.1
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.8