name: user_data
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../core
  core_ui:
    path: ../../core_ui
  domain:
    path: ../../domain
  navigation:
    path: ../../navigation
  user_categories:
    path: ../user_categories
  user_folders:
    path: ../user_folders
  private_folders:
    path: ../private_folders

dev_dependencies:
  lints: ^2.1.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.8