name: auth
description: Authorization module
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  app:
    path: ../../.
  core:
    path: ../../core
  core_ui:
    path: ../../core_ui
  navigation:
    path: ../../navigation
  domain:
    path: ../../domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.1.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

